# Generated by Django 5.0.6 on 2025-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('moeda', models.TextField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'ordering': ['data', 'moeda'],
                'unique_together': {('data', 'moeda')},
            },
        ),
    ]
