# Generated by Django 5.0.6 on 2025-06-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['data', 'moeda'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
    ]
